sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t xps17/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xps17/react-test npm test

after_success:
  - docker build -t xps17/multi-client ./client
  - docker build -t xps17/multi-nginx ./nginx
  - docker build -t xps17/multi-server ./server
  - docker build -t xps17/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push xps17/multi-client
  - docker push xps17/multi-nginx
  - docker push xps17/multi-server
  - docker push xps17/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-475522645261"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"