language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xps17/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xps17/react-test npm test

after_success:
  - docker build -t xps17/multi-client ./client
  - docker build -t xps17/multi-nginx ./nginx
  - docker build -t xps17/multi-server ./server
  - docker build -t xps17/multi-worker ./worker